# Generated by Django 4.1.4 on 2022-12-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("price", models.IntegerField()),
                ("num_bedrooms", models.IntegerField()),
                ("num_bathrooms", models.IntegerField()),
                ("sq_footage", models.IntegerField()),
                ("address", models.CharField(max_length=100)),
            ],
        ),
    ]
