# Generated by Django 4.1 on 2023-01-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.ImageField(default="", upload_to="image"),
        ),
    ]
