# Generated by Django 4.1 on 2023-01-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(default="", upload_to=""),
        ),
    ]
