# Generated by Django 4.1.5 on 2023-01-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cvcreator", "0003_rename_personaldetails_personalinfo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PersonalInfo",
        ),
    ]
