# Generated by Django 4.1.5 on 2023-01-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvcreator", "0007_alter_personalinfo_dob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfo",
            name="dob",
            field=models.DateField(
                help_text="Choose your date of birth", verbose_name="Date of Birth"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Please enter your email here", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="gender",
            field=models.CharField(
                choices=[("male", "MALE"), ("female", "FEMALE")],
                help_text="Select your Gender",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="idNumber",
            field=models.IntegerField(
                help_text="Enter your ID number",
                primary_key=True,
                serialize=False,
                verbose_name="ID Number",
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="language",
            field=models.CharField(
                help_text="What languages can you speak", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="maritalStatus",
            field=models.CharField(
                choices=[("married", "MARRIED"), ("single", "SINGLE")],
                help_text="Kindly choose your marital status here",
                max_length=30,
                verbose_name="Marital Status",
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="name",
            field=models.CharField(help_text="Enter full name", max_length=30),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="nationality",
            field=models.CharField(help_text="What's your nationality?", max_length=30),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="religion",
            field=models.CharField(
                blank=True, help_text="Please enter your religion here", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="telephone",
            field=models.CharField(help_text="Enter phone number here", max_length=30),
        ),
    ]
